Hw2
falseness/cpp_abbyy pull request #6
Opened 2023-10-23 02:03 UTC by falseness

2023-10-27 11:36 UTC, vindarten requested changes
Предварительная оценка: 9 баллов

2023-10-27 11:36 UTC, vindarten commented on task1-1-1/main.cpp
> +}
1 балл

2023-10-27 11:36 UTC, vindarten commented on task1-1-2/main.cpp
> +    std::cout << sum(filtered.begin(), filtered.end()) / std::distance(filtered.begin(), filtered.end());
есть `std::ranges::distance`, в него можно сунуть `filtered_keys` целиком

2023-10-27 11:36 UTC, vindarten commented on task1-1-2/main.cpp
> +}
1 балл

2023-10-27 11:36 UTC, vindarten commented on task1-1-3/main.cpp
> +}
1 балл

2023-10-27 11:36 UTC, vindarten commented on task1-1-4/main.cpp
> +}
1 балл

2023-10-27 11:36 UTC, vindarten commented on task1-3-1/main.cpp
> +    static_assert(CanBeConcatted<char, short>);
У меня для Вас есть задачка со звездочкой) Сможете написать свой кастомный класс, который пролезет во все эти концепты?

2023-10-27 11:36 UTC, vindarten commented on task1-3-1/main.cpp
> +}
1 балл

2023-10-27 11:36 UTC, vindarten commented on trapping-rain-water/solution.hpp
> +};
2 балла, но подумайте еще, как решить ровно за один проход)

2023-10-27 11:36 UTC, vindarten commented on interleaving-string/solution.hpp
> +};
2 балла

2023-11-06 10:35 UTC, falseness commented on task1-3-1/main.cpp
> +    static_assert(CanBeConcatted<char, short>);
нет

2023-11-10 17:00 UTC, falseness commented on task1-1-2/main.cpp
> +    std::cout << sum(filtered.begin(), filtered.end()) / std::distance(filtered.begin(), filtered.end());
поправил (4 дня назад)

2023-11-10 17:00 UTC, falseness commented on trapping-rain-water/solution.hpp
> +};
поправил (4 дня назад)

2023-11-25 23:04 UTC, vindarten approved these changes
Спасибо, что поправили замечания!
Итоговая оценка за задание останется 9 баллов (-1 за задачу про модули), но в конце курса я все равно добавлю баллы за работу на лекции.

2023-11-25 23:04 UTC, vindarten commented on task1-3-1/main.cpp
> +    static_assert(CanBeConcatted<char, short>);
Можно написать что-то вроде такого https://godbolt.org/z/EbdMP6Mnb
Я пытался намекнуть, что неплохо бы еще добавить ограничение на тип возвращаемого значения std::to_string()

2023-12-24 10:20 UTC, merged